In [2]:
import torch

# 1. Basic

## 1.1 Construct a tensor

In [8]:
#construct a 5*3 matrix
x = torch.empty(5,3)
print(x)
#construct a 5*3 matrix
x = torch.rand(5,3)
print(x)

#construct a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.0571e-42, 0.0000e+00],
        [0.0000e+00, 4.2246e-39, 0.0000e+00]])
tensor([[0.5455, 0.1735, 0.4184],
        [0.3836, 0.8486, 0.5562],
        [0.6455, 0.7959, 0.5787],
        [0.3247, 0.9681, 0.2473],
        [0.4826, 0.5575, 0.8955]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## 1.2 Operation

100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/stable/torch.html).

### Addition
we have 3 methods:(x and y are tensors in torch)
* `+`operation, e.g:x + y
* torch.add() method, e.g: torch.add(x, y) 
* tensor.add(tensor), e.g: y.add(x)

In [22]:
x,y = torch.rand(5, 3, dtype = torch.float), torch.rand(5, 3, dtype = torch.float)
print(x)
print(y)
print(x + y)

tensor([[0.1369, 0.0691, 0.2764],
        [0.8451, 0.2138, 0.7306],
        [0.7801, 0.5276, 0.9907],
        [0.1155, 0.8259, 0.9949],
        [0.7262, 0.9690, 0.1867]])
tensor([[0.3382, 0.4925, 0.8011],
        [0.4550, 0.1447, 0.9011],
        [0.3954, 0.4953, 0.5967],
        [0.8077, 0.6707, 0.4816],
        [0.7932, 0.4072, 0.7884]])
tensor([[0.4751, 0.5616, 1.0775],
        [1.3002, 0.3586, 1.6317],
        [1.1754, 1.0229, 1.5874],
        [0.9232, 1.4966, 1.4765],
        [1.5194, 1.3762, 0.9752]])


In [24]:
#Addition: providing an output tensor as argument
ans = torch.empty(x.size())
torch.add(x, y, out = ans)
print(ans)

tensor([[0.4751, 0.5616, 1.0775],
        [1.3002, 0.3586, 1.6317],
        [1.1754, 1.0229, 1.5874],
        [0.9232, 1.4966, 1.4765],
        [1.5194, 1.3762, 0.9752]])


In [25]:
print(y.add(x))
print(y)

tensor([[0.4751, 0.5616, 1.0775],
        [1.3002, 0.3586, 1.6317],
        [1.1754, 1.0229, 1.5874],
        [0.9232, 1.4966, 1.4765],
        [1.5194, 1.3762, 0.9752]])
tensor([[0.3382, 0.4925, 0.8011],
        [0.4550, 0.1447, 0.9011],
        [0.3954, 0.4953, 0.5967],
        [0.8077, 0.6707, 0.4816],
        [0.7932, 0.4072, 0.7884]])


### In-place

In [26]:
# Addition: in-place
print(y.add_(x))
print(y)

tensor([[0.4751, 0.5616, 1.0775],
        [1.3002, 0.3586, 1.6317],
        [1.1754, 1.0229, 1.5874],
        [0.9232, 1.4966, 1.4765],
        [1.5194, 1.3762, 0.9752]])
tensor([[0.4751, 0.5616, 1.0775],
        [1.3002, 0.3586, 1.6317],
        [1.1754, 1.0229, 1.5874],
        [0.9232, 1.4966, 1.4765],
        [1.5194, 1.3762, 0.9752]])


Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, **will change x.**

### Indexing

You can use standard NumPy-like indexing with all bells and whistles!

In [29]:
print(x[:,1]) #the 2nd column of x
print(x[:1])  #the 1st row of x

tensor([0.0691, 0.2138, 0.5276, 0.8259, 0.9690])
tensor([[0.1369, 0.0691, 0.2764]])


### Resizing

If you want to resize/reshape tensor, you can use `torch.view`

In [32]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
# only one element tensors can be converted to Python scalars
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7623])
0.7622635960578918


## 1.3 Numpy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will **share their underlying memory locations,** and changing one will change the other.

In [36]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
#See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [38]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# 2. Autograd: automatic differetiation

Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.